const $ = (id) => document.getElementById(id);
const data = { lettuce:{base:160,root:48,note:'Fast cycle · Leaf biomass · Veggie-tested'},radish:{base:118,root:41,note:'Compact cycle · Root crop · High germination'},basil:{base:92,root:35,note:'Aromatic herb · Slow cycle · Moisture-sensitive'} };
let gravity=0, playing=true, permission=localStorage.getItem('orbital-role')||'researcher', tick;
const canvas=$('rootCanvas'),ctx=canvas.getContext('2d');
function hash(n){return Math.abs(Math.sin(n*991.77)*43758.5453)%1}
function values(){const crop=data[$('species').value],m=+$('moisture').value,n=+$('nutrients').value/100,day=+$('day').value;const gravityFactor=.71+.29*gravity, moist=1-Math.abs(m-65)/190, speciesFactor=day/22;const biomass=Math.round(crop.base*gravityFactor*moist*n*speciesFactor);const score=Math.max(30,Math.min(96,Math.round(46+biomass/crop.base*48)));return {crop,m,n,day,biomass,score,root:(crop.root*gravityFactor*moist*speciesFactor).toFixed(1),expo:Math.round((48+gravity*25+(m-25)*.29)*n),earth:Math.round(crop.base*moist*n*speciesFactor)}}
function update(){const v=values();$('moistureValue').textContent=v.m+'%';$('nutrientValue').textContent=v.n.toFixed(2)+'×';$('dayValue').textContent=v.day+' D';$('speciesNote').textContent=v.crop.note;$('simTitle').textContent=(gravity===0?'Microgravity':gravity===1?'Earth control':gravity===.16?'Lunar gravity':'Martian gravity')+' / Day '+v.day;$('score').textContent=v.score;$('biomass').innerHTML=v.biomass+' <small>g / plant</small>';$('rootArea').innerHTML=v.root+' <small>cm²</small>';$('exposure').innerHTML=v.expo+'<small>%</small>';const delta=Math.round((1-v.biomass/v.earth)*100);$('delta').textContent=(delta>0?'−':'＋')+Math.abs(delta)+'% BIOMASS';$('earthBar').style.width=Math.min(100,v.biomass/v.earth*100)+'%';$('comparisonText').textContent='Earth-normal growth: '+v.earth+' g / plant under identical inputs';$('confidence').textContent=v.day<10?'LOWER CONFIDENCE':v.day<20?'MODERATE CONFIDENCE':'HIGHER CONFIDENCE';$('transportText').innerHTML='<i></i> '+(gravity<.2?'Diffusion-dominant transport':'Mixed diffusion / convection');$('insightTitle').textContent=gravity<.2?'The root system spreads laterally.':'Residual gravity restores a downward root bias.';draw(v)}
function draw(v){const w=canvas.width,h=canvas.height,species=$('species').value,medium=$('medium').value;
 const traits={lettuce:{seed:7,branches:10,spread:1.35,wave:.44,color:'94,230,218'},radish:{seed:29,branches:-8,spread:.68,wave:.22,color:'245,151,116'},basil:{seed:63,branches:4,spread:1.08,wave:.7,color:'189,177,255'}}[species];
 const mediumFactor={arcillite:.88,coco:1.15,gel:.72}[medium],wetness=(v.m-25)/65,nutrientPower=Math.max(.1,(v.n-.4));ctx.clearRect(0,0,w,h);const g=ctx.createRadialGradient(w/2,h*.34,5,w/2,h*.34,310);g.addColorStop(0,'#173a3a');g.addColorStop(.43,'#0c2427');g.addColorStop(1,'#07171a');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(160,220,198,.07)';ctx.lineWidth=1;for(let x=0;x<w;x+=46){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=46){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
 // Nutrient field: low moisture creates small isolated pockets; high moisture creates large overlapping plumes.
 const plumes=Math.round(5+wetness*23), plumeRadius=22+wetness*100+nutrientPower*42;for(let i=0;i<plumes;i++){let x=w*(.11+hash(i+v.day*2+traits.seed)*.78),y=h*(.16+hash(i+55+traits.seed)*.68),r=plumeRadius*(.55+hash(i+33)*.7);let rg=ctx.createRadialGradient(x,y,0,x,y,r);rg.addColorStop(0,`rgba(233,187,107,${.08+nutrientPower*.22})`);rg.addColorStop(.48,`rgba(233,187,107,${.025+nutrientPower*.05})`);rg.addColorStop(1,'rgba(233,187,107,0)');ctx.fillStyle=rg;ctx.fillRect(x-r,y-r,r*2,r*2)}
 const sx=w/2,sy=h*.32,branches=Math.round((15+v.day*1.55+traits.branches)*(1.25-wetness*.38)*mediumFactor);for(let b=0;b<branches;b++){let x=sx,y=sy,angle=(hash(b+11+traits.seed)-.5)*(gravity===0?2.8:1.6)*traits.spread+Math.PI/2,steps=4+Math.round(hash(b+5+traits.seed)*7+v.day*.27+(1-wetness)*5);ctx.beginPath();ctx.moveTo(x,y);for(let s=0;s<steps;s++){const down=(gravity-.18)*.17;angle+=(hash(b*91+s*13+traits.seed)-.5)*traits.wave+down;x+=Math.cos(angle)*(8+s*(1.15+wetness*.6)*mediumFactor);y+=Math.sin(angle)*(8+s*(1.15+wetness*.6)*mediumFactor);ctx.lineTo(x,y)}ctx.strokeStyle=`rgba(${traits.color},${.27+hash(b+traits.seed)*.58})`;ctx.lineWidth=Math.max(.7,2.7-b/branches*1.8);ctx.shadowColor=`rgb(${traits.color})`;ctx.shadowBlur=5;ctx.stroke();ctx.shadowBlur=0}
 // Radish retains a characteristic primary taproot, making crop selection obvious at a glance.
 if(species==='radish'){ctx.beginPath();ctx.moveTo(sx,sy);ctx.bezierCurveTo(sx-12,sy+80,sx+28,sy+150,sx+2,sy+225);ctx.strokeStyle='rgba(245,151,116,.95)';ctx.lineWidth=5;ctx.shadowColor='#f59774';ctx.shadowBlur=10;ctx.stroke();ctx.shadowBlur=0}ctx.fillStyle='#d9f593';ctx.beginPath();ctx.arc(sx,sy,5,0,Math.PI*2);ctx.fill()}
function run(){if(permission==='viewer'){alert('Viewer access can explore studies but cannot run new simulations. Choose Researcher access controls to continue.');return}const b=$('runButton');b.querySelector('span').textContent='CALCULATING FIELD…';b.disabled=true;setTimeout(()=>{b.querySelector('span').textContent='STUDY UPDATED ✓';update();setTimeout(()=>{b.querySelector('span').textContent='RUN GROWTH STUDY';b.disabled=false},1100)},500)}
document.querySelectorAll('#gravity button').forEach(b=>b.onclick=()=>{document.querySelector('#gravity .active').classList.remove('active');b.classList.add('active');gravity=+b.dataset.value;update()});['species','medium','moisture','nutrients','day'].forEach(id=>$(id).addEventListener('input',update));$('runButton').onclick=run;$('playButton').onclick=()=>{playing=!playing;$('playButton').textContent=playing?'Ⅱ':'▶'};$('exportButton').onclick=()=>{if(permission==='viewer'){alert('Export requires Researcher access.');return}const report={project:'Orbital Grove',generatedAt:new Date().toISOString(),role:permission,gravity,inputs:{species:$('species').value,medium:$('medium').value,moisture:+$('moisture').value,nutrientDensity:+$('nutrients').value/100,days:+$('day').value},result:values(),method:'Physics-based parametric model using diffusion-dominant transport and biased random-walk root architecture.'};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));a.download='orbital-grove-study.json';a.click();URL.revokeObjectURL(a.href)};
const dialog=$('permissionDialog');$('permissionsButton').onclick=()=>dialog.showModal();document.querySelectorAll('#roles button').forEach(b=>b.onclick=()=>{document.querySelector('#roles .selected').classList.remove('selected');b.classList.add('selected');permission=b.dataset.role});$('savePermission').onclick=()=>{localStorage.setItem('orbital-role',permission);dialog.close()};document.querySelector(`#roles [data-role="${permission}"]`).classList.add('selected');document.querySelectorAll('#roles button').forEach(b=>{if(b.dataset.role!==permission)b.classList.remove('selected')});
tick=setInterval(()=>{if(playing){let d=+$('day').value; $('day').value=d>=30?1:d+1;update()}},1800);update();
